import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {once} from 'node:events';

const ROOT=process.cwd(), TMP=path.join(ROOT,'.audit-tmp');
fs.rmSync(TMP,{recursive:true,force:true}); fs.mkdirSync(TMP,{recursive:true});
const fails=[], passed=[];
function ok(v,m){(v?passed:fails).push(m); console.log((v?'PASS: ':'FAIL: ')+m)}
function pdf(name,pages,id,bad=false){const b=Buffer.alloc(24);b.writeUInt16BE(pages,0);b[2]=id;b[3]=bad?255:0;const p=path.join(TMP,name);fs.writeFileSync(p,b);return p}
const same=pdf('same.pdf',12,1), other=pdf('other.pdf',7,2), huge=pdf('huge.pdf',2000,3), corrupt=pdf('corrupt.pdf',3,255,true);
const txt=path.join(TMP,'bad.txt');fs.writeFileSync(txt,'x');
const png=path.join(TMP,'pixel.png');fs.writeFileSync(png,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAFElEQVR42mNk+M/wn4GBgYGJAQoAHgAB/1V1VgAAAABJRU5ErkJggg==','base64'));
const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{try{let u=new URL(req.url,'http://x').pathname;if(u==='/')u='/index.html';const f=path.resolve(ROOT,'.'+decodeURIComponent(u));if(!f.startsWith(ROOT+path.sep))throw 0;const s=fs.statSync(f);if(!s.isFile())throw 0;res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');fs.createReadStream(f).pipe(res)}catch{res.writeHead(404);res.end('x')}});
server.listen(0,'127.0.0.1');await once(server,'listening');const url='http://127.0.0.1:'+server.address().port+'/';
function chromeBin(){if(process.env.CHROME_BIN&&fs.existsSync(process.env.CHROME_BIN))return process.env.CHROME_BIN;for(const n of ['google-chrome','google-chrome-stable','chromium','chromium-browser']){const r=spawnSync('which',[n],{encoding:'utf8'});if(r.status===0&&r.stdout.trim())return r.stdout.trim()}return null}
const bin=chromeBin();if(!bin){console.error('Chrome missing');process.exit(1)}
const chrome=spawn(bin,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--remote-debugging-pipe','--window-size=1440,1000','about:blank'],{stdio:['ignore','ignore','inherit','pipe','pipe']});
class C{constructor(p){this.p=p;this.id=1;this.pending=new Map;this.buf=Buffer.alloc(0);p.stdio[4].on('data',x=>this.on(x))}on(x){this.buf=Buffer.concat([this.buf,x]);let i;while((i=this.buf.indexOf(0))>=0){const s=this.buf.subarray(0,i).toString();this.buf=this.buf.subarray(i+1);if(!s)continue;let m;try{m=JSON.parse(s)}catch{continue}if(m.id&&this.pending.has(m.id)){const h=this.pending.get(m.id);this.pending.delete(m.id);m.error?h.j(new Error(m.error.message)):h.r(m.result||{})}}}send(method,params={},sessionId){const id=this.id++,m={id,method,params};if(sessionId)m.sessionId=sessionId;return new Promise((r,j)=>{const t=setTimeout(()=>{this.pending.delete(id);j(new Error('CDP timeout '+method))},20000);this.pending.set(id,{r:x=>{clearTimeout(t);r(x)},j:e=>{clearTimeout(t);j(e)}});this.p.stdio[3].write(JSON.stringify(m)+'\0')})}}
const cdp=new C(chrome);await new Promise(r=>setTimeout(r,300));const t=await cdp.send('Target.createTarget',{url:'about:blank'});const a=await cdp.send('Target.attachToTarget',{targetId:t.targetId,flatten:true});const S=(m,p={})=>cdp.send(m,p,a.sessionId);await S('Page.enable');await S('Runtime.enable');await S('DOM.enable');
const mock="(()=>{window.__exportLog=[];window.__downloads=[];const nr=v=>((v%360)+360)%360;window.pdfjsLib={GlobalWorkerOptions:{},getDocument:({data})=>{const b=data instanceof Uint8Array?data:new Uint8Array(data||[]),n=Math.max(1,((b[0]||0)<<8)|(b[1]||1)),id=b[2]||0,bad=b[3]===255;return{onPassword:null,destroy(){},promise:bad?Promise.reject(new Error('bad')):Promise.resolve({numPages:n,destroy:()=>Promise.resolve(),getPage:async()=>({rotate:0,getViewport:({scale=1,rotation=0}={})=>{let w=612,h=792;if(nr(rotation)%180){const q=w;w=h;h=q}return{width:w*scale,height:h*scale}},render:({canvasContext,viewport})=>{try{canvasContext.fillStyle='#fff';canvasContext.fillRect(0,0,viewport.width,viewport.height)}catch{}return{promise:Promise.resolve(),cancel(){}}}})})}}};class P{constructor(id,i){this.sourceId=id;this.index=i;this.angle=0}getRotation(){return{angle:this.angle}}setRotation(r){this.angle=r.angle}getCropBox(){return{x:0,y:0,width:612,height:792}}getWidth(){return 612}getHeight(){return 792}drawImage(){window.__exportLog.push({type:'overlay',sourceId:this.sourceId,index:this.index})}}window.PDFLib={degrees:angle=>({angle}),PDFDocument:{load:async bytes=>{const b=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes||[]);return{__sourceId:b[2]||0}},create:async()=>{const pages=[];return{copyPages:async(src,idxs)=>idxs.map(i=>{window.__exportLog.push({type:'copy',sourceId:src.__sourceId,index:i});return new P(src.__sourceId,i)}),addPage:p=>pages.push(p),embedPng:async()=>({}),save:async()=>{window.__exportLog.push({type:'save',count:pages.length});return new Uint8Array([37,80,68,70])}}}}};HTMLAnchorElement.prototype.click=function(){window.__downloads.push({download:this.download||'',href:this.href||''})}})();";
await S('Page.addScriptToEvaluateOnNewDocument',{source:mock});
async function E(x){const r=await S('Runtime.evaluate',{expression:x,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result?.value}
async function W(x,ms=12000){const st=Date.now();while(Date.now()-st<ms){try{const v=await E(x);if(v)return v}catch{}await new Promise(r=>setTimeout(r,80))}throw new Error('wait '+x)}
async function nav(w=1440,h=1000,mobile=false){await S('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:mobile?2:1,mobile});await S('Page.navigate',{url:url+'?t='+Date.now()});await W("document.readyState==='complete'&&!!document.querySelector('#fileInput')")}
async function node(sel){const d=await S('DOM.getDocument',{depth:1});const q=await S('DOM.querySelector',{nodeId:d.root.nodeId,selector:sel});if(!q.nodeId)throw new Error('missing '+sel);return q.nodeId}
async function files(sel,arr){await S('DOM.setFileInputFiles',{nodeId:await node(sel),files:arr})}
async function click(sel){const q=JSON.stringify(sel);if(!await E("(()=>{const e=document.querySelector("+q+");if(!e)return false;e.click();return true})()"))throw new Error('click '+sel)}
async function textClick(sel,text){const s=JSON.stringify(sel),t=JSON.stringify(text);if(!await E("(()=>{const e=[...document.querySelectorAll("+s+")].find(x=>x.textContent.trim()==="+t+");if(!e)return false;e.click();return true})()"))throw new Error('text click '+text)}
async function draw(tool,x1,y1,x2,y2){await textClick('.pdf-editor-tool',tool);await E("(()=>{const e=document.querySelector('.pdf-editor-overlay'),r=e.getBoundingClientRect(),f=(t,x,y,b)=>e.dispatchEvent(new PointerEvent(t,{bubbles:true,cancelable:true,pointerId:77,pointerType:'mouse',button:0,buttons:b,clientX:r.left+r.width*x,clientY:r.top+r.height*y}));f('pointerdown',"+x1+","+y1+",1);for(let i=1;i<=6;i++){const z=i/6;f('pointermove',"+x1+"+("+x2+"-"+x1+")*z,"+y1+"+("+y2+"-"+y1+")*z,1)}f('pointerup',"+x2+","+y2+",0);return true})()")}
async function drag(i,j,touch=false){const p=await E("(()=>{const a=[...document.querySelectorAll('.sidebar-thumb-wrap')],f=k=>{const r=a[k].getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2}};return{a:f("+i+"),b:f("+j+")}})()");if(touch){await S('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p.a.x,y:p.a.y,id:1,radiusX:4,radiusY:4}]});for(let k=1;k<=5;k++){const z=k/5;await S('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:p.a.x+(p.b.x-p.a.x)*z,y:p.a.y+(p.b.y-p.a.y)*z,id:1,radiusX:4,radiusY:4}]})}await S('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}else{await S('Input.dispatchMouseEvent',{type:'mousePressed',x:p.a.x,y:p.a.y,button:'left',buttons:1,clickCount:1});for(let k=1;k<=6;k++){const z=k/6;await S('Input.dispatchMouseEvent',{type:'mouseMoved',x:p.a.x+(p.b.x-p.a.x)*z,y:p.a.y+(p.b.y-p.a.y)*z,button:'left',buttons:1})}await S('Input.dispatchMouseEvent',{type:'mouseReleased',x:p.b.x,y:p.b.y,button:'left',buttons:0,clickCount:1})}}
try{
await nav();
await files('#fileInput',[txt]);await new Promise(r=>setTimeout(r,200));ok(await E("document.querySelectorAll('.document-chip').length===0"),'non-PDF rejected');
await files('#fileInput',[corrupt]);await new Promise(r=>setTimeout(r,250));ok(await E("document.querySelectorAll('.document-chip').length===0"),'corrupt PDF fails cleanly');
await files('#fileInput',[same]);await W("document.querySelectorAll('.sidebar-page-row').length===12");await W("document.querySelector('.pdf-editor-overlay')?.clientWidth>100");ok(true,'first PDF opens inline');
await files('#fileInput',[same]);await W("document.querySelectorAll('.sidebar-page-row').length===24");const names=await E("[...document.querySelectorAll('.document-name')].map(e=>e.textContent)");ok(names[0]==='same.pdf'&&names[1].includes('copy 2'),'same PDF can be added twice');
await files('#fileInput',[other]);await W("document.querySelectorAll('.sidebar-page-row').length===31");ok(await E("document.querySelectorAll('.document-chip').length===3"),'multi-PDF combine rail');
const b=await E("[...document.querySelectorAll('.sidebar-page-row')].map(e=>e.dataset.pageId)");await drag(0,5);await new Promise(r=>setTimeout(r,250));const d=await E("[...document.querySelectorAll('.sidebar-page-row')].map(e=>e.dataset.pageId)");ok(b[0]!==d[0]&&d.includes(b[0]),'desktop drag reorder');
await E("document.querySelectorAll('.sidebar-page-row')[3].click()");await W("document.querySelectorAll('.sidebar-page-row')[3].classList.contains('is-active')");const pid=await E("document.querySelector('.sidebar-page-row.is-active').dataset.pageId");
await draw('Pen',.2,.2,.65,.27);await draw('Highlight',.15,.34,.7,.4);await textClick('.pdf-editor-btn','Undo');await textClick('.pdf-editor-btn','Redo');await draw('Rectangle',.18,.46,.62,.62);await draw('Whiteout',.22,.68,.55,.75);await E("window.prompt=()=>\"Audit text\"");await textClick('.pdf-editor-tool','Text');await E("(()=>{const e=document.querySelector('.pdf-editor-overlay'),r=e.getBoundingClientRect();e.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:88,pointerType:'mouse',button:0,buttons:1,clientX:r.left+r.width*.25,clientY:r.top+r.height*.82}));return true})()");await textClick('.pdf-editor-tool','Image');await files('.pdf-editor-hidden-input',[png]);await new Promise(r=>setTimeout(r,250));await textClick('.pdf-editor-btn','Save');const types=await E("window.iWeatherPDFEditorHost.getAnnotations("+JSON.stringify(pid)+").map(x=>x.type)");for(const t of ['pen','highlight','rect','whiteout','text','image'])ok(types.includes(t),'edit tool '+t+' persists');
await textClick('.inspector-action','Rotate right');await W("window.iWeatherPDFEditorHost.getPage("+JSON.stringify(pid)+")?.rotation===90");ok(true,'rotation persists');
const n=await E("document.querySelectorAll('.sidebar-page-row').length");await textClick('.inspector-action','Duplicate');await W("document.querySelectorAll('.sidebar-page-row').length==="+(n+1));await click('#undoButton');await W("document.querySelectorAll('.sidebar-page-row').length==="+n);await click('#redoButton');await W("document.querySelectorAll('.sidebar-page-row').length==="+(n+1));ok(true,'duplicate + workspace undo/redo');
await E("window.__exportLog=[];window.__downloads=[]");await click('#exportButton');await W("window.__exportLog.some(x=>x.type==='save')");const ex=await E("({copies:window.__exportLog.filter(x=>x.type==='copy').length,save:window.__exportLog.filter(x=>x.type==='save').at(-1)?.count,over:window.__exportLog.filter(x=>x.type==='overlay').length,dl:window.__downloads.at(-1)?.download||''})");const pc=await E("document.querySelectorAll('.sidebar-page-row').length");ok(ex.copies===pc&&ex.save===pc&&ex.over>0&&ex.dl.endsWith('.pdf'),'full export order/count/edit overlay/download');
await E("(()=>{const r=document.querySelectorAll('.sidebar-page-row');r[0].dispatchEvent(new MouseEvent('click',{bubbles:true}));r[2].dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:true}));return true})()");await W("document.querySelectorAll('.sidebar-page-row.is-selected').length===2");await click('[data-tool=\"split\"]');await E("window.__exportLog=[]");await click('#exportButton');await W("window.__exportLog.some(x=>x.type==='save')");ok(await E("window.__exportLog.filter(x=>x.type==='copy').length===2"),'split exports selected only');
const dc=await E("document.querySelectorAll('.document-chip').length");await E("document.querySelector('.document-remove').click()");await W("document.querySelectorAll('.document-chip').length==="+(dc-1));await files('#fileInput',[same]);await W("document.querySelectorAll('.document-chip').length==="+dc);const rn=await E("[...document.querySelectorAll('.document-name')].map(e=>e.textContent)");ok(new Set(rn).size===rn.length,'remove and re-add same PDF labels stay unique');
const dd=await E("document.querySelectorAll('.document-chip').length");await E("(()=>{const f=new File([new Uint8Array([0,4,9,0])],'drop.pdf',{type:'application/pdf'}),d=new DataTransfer();d.items.add(f);window.dispatchEvent(new DragEvent('dragenter',{bubbles:true,dataTransfer:d}));window.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:d}));return true})()");await W("document.querySelectorAll('.document-chip').length==="+(dd+1));ok(true,'global file drop');
await nav();const st=Date.now();await files('#fileInput',[huge]);await W("document.querySelectorAll('.sidebar-page-row').length===2000",30000);const ms=Date.now()-st;ok(ms<30000,'2000-page workspace interactive under 30s ('+ms+'ms)');await E("document.querySelector('.sidebar-pages').scrollTop=document.querySelector('.sidebar-pages').scrollHeight");await new Promise(r=>setTimeout(r,450));const rb=await E("[...document.querySelectorAll('.sidebar-thumb-wrap canvas')].filter(c=>c.dataset.rendered==='true').length");ok(rb<=80,'large-workspace rendered thumbnails bounded at bottom ('+rb+')');await E("document.querySelector('.sidebar-pages').scrollTop=0");await new Promise(r=>setTimeout(r,450));const rt=await E("[...document.querySelectorAll('.sidebar-thumb-wrap canvas')].filter(c=>c.dataset.rendered==='true').length");ok(rt<=80,'large-workspace rendered thumbnails bounded at top ('+rt+')');const heap=await S('Runtime.getHeapUsage');ok(heap.usedSize<220*1024*1024,'2000-page JS heap under 220MB ('+Math.round(heap.usedSize/1048576)+'MB)');
await nav(390,844,true);await files('#fileInput',[same]);await W("document.querySelectorAll('.sidebar-page-row').length===12");await W("document.querySelector('.pdf-editor-overlay')?.clientWidth>100");const ml=await E("(()=>{const s=document.querySelector('.sidebar'),e=document.querySelector('.pdf-editor-embed');return{sw:s.getBoundingClientRect().width,sd:getComputedStyle(s).display,er:e.getBoundingClientRect().right,v:innerWidth,b:document.body.scrollWidth}})()");ok(ml.sd!=='none'&&ml.sw>=80,'mobile page rail visible');ok(ml.er<=ml.v+2&&ml.b<=ml.v+2,'mobile editor has no page overflow');const mb=await E("[...document.querySelectorAll('.sidebar-page-row')].map(e=>e.dataset.pageId)");await drag(0,2,true);await new Promise(r=>setTimeout(r,300));const ma=await E("[...document.querySelectorAll('.sidebar-page-row')].map(e=>e.dataset.pageId)");ok(mb[0]!==ma[0]&&ma.includes(mb[0]),'touch drag reorder');const rs=await E("(async()=>{for(let q=0;q<6;q++)for(let i=0;i<10;i++){document.querySelectorAll('.sidebar-page-row')[i].click();await new Promise(r=>setTimeout(r,10))}await new Promise(r=>setTimeout(r,200));return{a:document.querySelectorAll('.sidebar-page-row.is-active').length,e:document.querySelectorAll('.pdf-editor-embed').length}})()");ok(rs.a===1&&rs.e===1,'rapid page switching leaves one active editor');
}catch(e){fails.push('harness '+(e.stack||e));console.error(e)}finally{try{await cdp.send('Browser.close')}catch{}server.close();fs.rmSync(TMP,{recursive:true,force:true})}
console.log('\nBrowser stress: '+passed.length+' passed, '+fails.length+' failed');if(fails.length){for(const f of fails)console.error(' - '+f);process.exit(1)}
